import type { Metadata, Viewport } from "next";
import { notFound } from "next/navigation";
import "../globals.css";

import { locales, isLocale, localeMeta, href, languageAlternates, type Locale } from "@/lib/i18n";
import { site, siteUrl } from "@/lib/site";
import { fontVariables } from "@/lib/fonts";
import { getDictionary } from "@/content";
import { graph, personSchema, websiteSchema, professionalServiceSchema } from "@/lib/seo";

import { Providers } from "@/components/providers/Providers";
import { Nav } from "@/components/layout/Nav";
import { Footer } from "@/components/layout/Footer";
import { JsonLd } from "@/components/ui/JsonLd";
import { SmoothScroll } from "@/components/motion/SmoothScroll";
import { ScrollProgress } from "@/components/motion/ScrollProgress";
import { Cursor } from "@/components/motion/Cursor";
import { Preloader } from "@/components/motion/Preloader";
import { BackToTop } from "@/components/motion/BackToTop";
import { PageTransition } from "@/components/motion/PageTransition";

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: site.brand.dark },
    { media: "(prefers-color-scheme: light)", color: site.brand.light },
  ],
  colorScheme: "dark light",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale: raw } = await params;
  if (!isLocale(raw)) return {};
  const locale = raw;
  const dict = getDictionary(locale);

  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: dict.meta.home.title,
      template: `%s — ${site.name}`,
    },
    description: dict.meta.home.description,
    applicationName: site.name,
    authors: [{ name: site.person.name, url: siteUrl }],
    creator: site.person.name,
    publisher: site.person.name,
    generator: "Next.js",
    category: "technology",
    keywords: [...dict.meta.home.keywords],
    alternates: {
      canonical: `${siteUrl}${href(locale)}`,
      languages: languageAlternates("/", siteUrl),
    },
    manifest: "/manifest.webmanifest",
    // /icon and /apple-icon are generated by app/icon.tsx and app/apple-icon.tsx;
    // the SVG is listed first so browsers that support it use the crisp mark.
    icons: {
      icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
    },
    formatDetection: { telephone: false, address: false, email: false },
    referrer: "origin-when-cross-origin",
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const locale = raw as Locale;

  const dict = getDictionary(locale);
  const { htmlLang, dir } = localeMeta[locale];

  const structuredData = graph([
    personSchema(locale),
    websiteSchema(locale),
    professionalServiceSchema(locale, dict.meta.home.description),
  ]);

  return (
    <html lang={htmlLang} dir={dir} suppressHydrationWarning className={fontVariables}>
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <JsonLd data={structuredData} />
      </head>
      <body className="relative min-h-screen bg-bg text-txt antialiased">
        <Providers>
          <a
            href="#main"
            className="label-plain sr-only focus:not-sr-only focus:fixed focus:start-4 focus:top-4 focus:z-[300] focus:bg-accent focus:px-4 focus:py-2 focus:text-[12px] focus:text-on-accent"
          >
            {locale === "ar" ? "تخطَّ إلى المحتوى" : "Skip to content"}
          </a>

          <Preloader />
          <SmoothScroll />
          <ScrollProgress rtl={dir === "rtl"} />
          <Cursor viewLabel={locale === "ar" ? "افتح" : "View"} />

          <div aria-hidden="true" className="ambient" />
          <div aria-hidden="true" className="grain" />

          <Nav locale={locale} dict={dict} />

          <main id="main" className="relative z-10">
            <PageTransition>{children}</PageTransition>
          </main>

          <Footer locale={locale} dict={dict} />
          <BackToTop label={dict.footer.backToTop} />
        </Providers>
      </body>
    </html>
  );
}
